# Generated by Django 3.1.2 on 2020-10-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("schedules", "0002_task")]

    operations = [
        migrations.AddField(
            model_name="task", name="title", field=models.TextField(default="")
        )
    ]
